In [1]:
# Homework 6

In [2]:
import numpy as np

In [3]:
# 3.1
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [4]:
arr = np.array(list)

In [5]:
print(arr * 4)

[ 80 108  36  48 124  68  16 200 156 140]


In [6]:
print(np.mean(arr))

24.4


In [7]:
print(np.median(arr))

23.5


In [8]:
print(np.std(arr))

13.828955130450023


In [9]:
print(np.argmin(arr))
print(np.argmax(arr))

6
7


In [10]:
print(arr[6])
print(arr[7])

4
50


In [11]:
print(np.min(arr))
print(np.max(arr))

4
50


In [12]:
new_array = arr[arr > 20]
print(new_array)

[27 31 50 39 35]


In [13]:
# 3.2
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
arr2 = np.array(matrix)

In [14]:
arr2.shape
# 3 rows, 4 columns

(3, 4)

In [15]:
print(arr2[:, 2])

[17 14 19]


In [16]:
print(arr2[1, :])

[ 8 21 14  3]


In [17]:
print(arr2 * 2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [18]:
print(np.mean(arr2, axis=0))

[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [19]:
print(np.mean(arr2))

11.5


In [20]:
print(np.max(arr2, axis=1))
print(np.min(arr2, axis=0))

[17 21 19]
[ 5 12 14  3]


In [21]:
arr2 = arr2.flatten()
# the array is now one dimensional (no columns)

In [22]:
print(np.argmin(arr2))
print(np.argmax(arr2))

7
5


In [23]:
new_arr2 = arr[arr > 15]
new_arr2

array([20, 27, 31, 17, 50, 39, 35])

In [24]:
np.sort(new_arr2)

array([17, 20, 27, 31, 35, 39, 50])

In [25]:
# 4: Prime star systems

In [26]:
arr = np.array([
    [2, 3, 5],
    [14, 6, 8], 
    [11, 13, 17],
    [7, 10, 13]
])

def is_prime(num):
    if num == 2:
        return True
    for i in range(2, num):
        if num % i == 0:
            return False
        else:
            return True

def prime_rows(my_array):
    new_array = []
    for i in my_array:
        if any(is_prime(k) for k in i):
                new_array.append(i)
    return np.array(new_array)

print(prime_rows(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [27]:
# 5: Let's play checkers

In [28]:
# 5.1
def blank_square(n):
    return np.empty((n, n), dtype = int)

print(blank_square(8))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [29]:
# 5.2
def half_checkerboard(n):
    board = np.empty((n, n), dtype = int)
    pattern = ([1, 0] * 4)
    board[::2] = pattern
    return board
print(half_checkerboard(8))

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [30]:
# 5.3
def checkerboard(n):
    board = np.empty((n, n), dtype = int)
    pattern1 = ([1, 0] * 4)
    pattern2 = ([0, 1] * 4)
    board[::2] = pattern1
    board[1::2] = pattern2
    return board

print(checkerboard(8))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [31]:
# 5.4
def reverse_checkerboard(n):
    board = np.empty((n, n), dtype = int)
    pattern1 = ([0, 1] * 4)
    pattern2 = ([1, 0] * 4)
    board[::2] = pattern1
    board[1::2] = pattern2
    return board

print(reverse_checkerboard(8))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [32]:
# 6 The expanding universe

In [42]:
def expansion(arr, num):
    spaces = " " * num
    return np.array([spaces.join(word) for word in arr])
    
universe = np.array(["galaxy", "clusters"])

print(expansion(universe, 1))
print(expansion(universe, 3))

['g a l a x y' 'c l u s t e r s']
['g   a   l   a   x   y' 'c   l   u   s   t   e   r   s']


In [43]:
# 7 Second-Brightest Star

In [62]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1622  606  573 1346  951]


In [63]:
def secondBrightest(arr):
    new_array = []
    for row in arr:
        min_mag = np.min(row)
        second_lowest_mag = 2000
        for star in row:
            if star > min_mag and star < second_lowest_mag:
                second_lowest_mag = star
        new_array.append(second_lowest_mag)
    return np.array(new_array)

print(secondBrightest(stars))

[1622  606  573 1346  951]
