In [160]:
# Homework 6

In [161]:
import numpy as np

In [162]:
# 3.1
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [163]:
arr = np.array(list)

In [164]:
print(arr * 4)

[ 80 108  36  48 124  68  16 200 156 140]


In [165]:
print(np.mean(arr))

24.4


In [166]:
print(np.median(arr))

23.5


In [167]:
print(np.std(arr))

13.828955130450023


In [168]:
print(np.argmin(arr))
print(np.argmax(arr))

6
7


In [169]:
print(arr[6])
print(arr[7])

4
50


In [170]:
print(np.min(arr))
print(np.max(arr))

4
50


In [171]:
new_array = arr[arr > 20]
print(new_array)

[27 31 50 39 35]


In [185]:
# 3.2
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
arr2 = np.array(matrix)

In [186]:
arr2.shape
# 3 rows, 4 columns

(3, 4)

In [187]:
print(arr2[:, 2])

[17 14 19]


In [188]:
print(arr2[1, :])

[ 8 21 14  3]


In [189]:
print(arr2 * 2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [190]:
print(np.mean(arr2, axis=0))

[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [191]:
print(np.mean(arr2))

11.5


In [192]:
print(np.max(arr2, axis=1))
print(np.min(arr2, axis=0))

[17 21 19]
[ 5 12 14  3]


In [193]:
arr2 = arr2.flatten()
# the array is now one dimensional (no columns)

In [194]:
print(np.argmin(arr2))
print(np.argmax(arr2))

7
5


In [195]:
new_arr2 = arr[arr > 15]
new_arr2

array([20, 27, 31, 17, 50, 39, 35])

In [196]:
np.sort(new_arr2)

array([17, 20, 27, 31, 35, 39, 50])

In [197]:
# --- 4 ---

In [199]:
arr = np.array([
    [2, 3, 5],
    [14, 6, 8], 
    [11, 13, 17],
    [7, 10, 13]
])

def is_prime(num):

def prime_rows(my_array):
    for i in my_array:
        for k in i:
            if k
    return 